#!/usr/bin/env python3
# epubveri for Sigil — the plugin icon, and the one place its geometry lives
# Copyright (C) 2026 Baris Kayadelen
#
# This program is free software: you can redistribute it and/or modify it
# under the terms of the GNU General Public License as published by the Free
# Software Foundation, either version 3 of the License, or (at your option)
# any later version. See the LICENSE file at the root of this repository.
"""Write `plugin.svg` and `plugin.png` from one description of the mark.

    python3 plugins/sigil/icon.py

**Why this exists rather than two hand-kept files.** Sigil looks for
`plugin.svg` and falls back to `plugin.png`, so the two have to agree, and
nothing checks that they do — a mark edited in one and not the other is a
difference only somebody running the other platform would ever see. The
geometry below is the single source and both files are generated from it.

**Why it rasterises itself.** A PNG needs a rasteriser, and the ones a
contributor might have (rsvg-convert, Inkscape, cairosvg, Pillow) are four
different answers to install. `zlib` and `struct` are in the standard library,
the mark is three shapes, and antialiasing from 36 coverage samples per pixel
is exact where a distance approximation goes wrong at corners. It takes about
a second.

**The mark.** A document silhouette with its top-right corner turned back and
a tick knocked out of it, on nothing. It carries its own contrast, so no theme
shows through it — but the outline is the mark itself rather than a rectangle
drawn around one, which is what lets it sit in a toolbar among glyphs that are
strokes on nothing.

DiapDealer, who maintains Sigil, put the constraint this way (MobileRead
374939 #22): *"Sigil can have just about any theme colors imaginable on Linux.
Simpler is best when including icons that may need to be visible in any theme
from light to dark (and in between) on three platforms."* The tile this
replaces was legible everywhere and read as a badge dropped into a row of
glyphs; a single-colour glyph would fit the row and disappear on a ground near
its own colour. This is the third answer.
"""

import math
import os
import struct
import sys
import zlib

HERE = os.path.dirname(os.path.abspath(__file__))

#: Everything is described on a 64 grid, which is the SVG's viewBox. The mark
#: fills 44x60 of it: as tall as a full-bleed tile would be, so it does not
#: read small beside one, and narrow enough to still be a page.
GRID = 64.0

PAGE = (0x1b, 0x5f, 0x7a)     #: the body
FOLD = (0x8f, 0xbc, 0xcd)     #: the turned-back corner, lighter
TICK = (0xff, 0xff, 0xff)     #: knocked out, so it reads on the body alone

RECT = (10.0, 2.0, 54.0, 62.0)                        #: x0, y0, x1, y1
RADIUS = 4.0
#: The page keeps `x - y - CUT <= 0`, which removes the corner above the
#: diagonal from (41, 2) to (54, 15). The fold triangle is then drawn *inside*
#: the page, below the same diagonal — cut plus tint is what reads as a fold.
CUT = 39.0
FOLD_TRI = [(41.0, 2.0), (54.0, 15.0), (41.0, 15.0)]
#: Two segments, round caps and joins. Nothing here is under 5 units, so at
#: 16 px the thinnest thing on screen is about 1.75 px.
TICK_PTS = [(19.0, 33.0), (28.0, 43.0), (45.0, 22.0)]
TICK_WIDTH = 7.0

SVG = '''<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by icon.py — edit the geometry there, not this file. -->
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 64 64" width="64"
     height="64" role="img" aria-label="epubveri">
  <title>epubveri</title>
  <path d="M14 2h27l13 13v43a4 4 0 0 1-4 4H14a4 4 0 0 1-4-4V6a4 4 0 0 1 4-4z"
        fill="#1b5f7a"/>
  <path d="M41 2l13 13H41z" fill="#8fbccd"/>
  <path d="M19 33l9 10 17-21" fill="none" stroke="#ffffff" stroke-width="7"
        stroke-linecap="round" stroke-linejoin="round"/>
</svg>
'''


def _in_round_rect(x, y):
    x0, y0, x1, y1 = RECT
    cx, cy = (x0 + x1) / 2, (y0 + y1) / 2
    hx, hy = (x1 - x0) / 2 - RADIUS, (y1 - y0) / 2 - RADIUS
    qx, qy = abs(x - cx) - hx, abs(y - cy) - hy
    if qx <= 0 or qy <= 0:
        return max(qx, qy) <= RADIUS
    return math.hypot(qx, qy) <= RADIUS


def _in_page(x, y):
    return _in_round_rect(x, y) and (x - y - CUT) <= 0


def _in_fold(x, y):
    def side(a, b):
        return (b[0] - a[0]) * (y - a[1]) - (b[1] - a[1]) * (x - a[0])
    a, b, c = FOLD_TRI
    s = (side(a, b), side(b, c), side(c, a))
    return all(v >= 0 for v in s) or all(v <= 0 for v in s)


def _in_tick(x, y):
    half = TICK_WIDTH / 2
    for (ax, ay), (bx, by) in zip(TICK_PTS, TICK_PTS[1:]):
        ex, ey = bx - ax, by - ay
        t = ((x - ax) * ex + (y - ay) * ey) / (ex * ex + ey * ey)
        t = min(1.0, max(0.0, t))
        if math.hypot(x - (ax + t * ex), y - (ay + t * ey)) <= half:
            return True
    return False


def _pixels(size, samples=6):
    """RGBA rows with a leading PNG filter byte, straight-alpha."""
    out = bytearray()
    step = GRID / size
    sub = step / samples
    total = float(samples * samples)
    for row in range(size):
        out.append(0)                                  # filter: none
        for col in range(size):
            r = g = b = hits = 0.0
            for sy in range(samples):
                y = row * step + (sy + 0.5) * sub
                for sx in range(samples):
                    x = col * step + (sx + 0.5) * sub
                    if not _in_page(x, y):
                        continue
                    if _in_tick(x, y):
                        c = TICK
                    elif _in_fold(x, y):
                        c = FOLD
                    else:
                        c = PAGE
                    r += c[0]; g += c[1]; b += c[2]; hits += 1
            if hits:
                out += bytes((int(r / hits + .5), int(g / hits + .5),
                              int(b / hits + .5), int(255 * hits / total + .5)))
            else:
                out += b"\x00\x00\x00\x00"
    return bytes(out)


def write_png(path, size=128):
    def chunk(tag, data):
        return (struct.pack(">I", len(data)) + tag + data
                + struct.pack(">I", zlib.crc32(tag + data) & 0xffffffff))
    head = struct.pack(">IIBBBBB", size, size, 8, 6, 0, 0, 0)
    blob = (b"\x89PNG\r\n\x1a\n" + chunk(b"IHDR", head)
            + chunk(b"IDAT", zlib.compress(_pixels(size), 9))
            + chunk(b"IEND", b""))
    with open(path, "wb") as handle:
        handle.write(blob)
    return len(blob)


def main():
    svg = os.path.join(HERE, "plugin.svg")
    png = os.path.join(HERE, "plugin.png")
    with open(svg, "w", encoding="utf-8") as handle:
        handle.write(SVG)
    print("%s  (%d bytes)" % (svg, len(SVG.encode("utf-8"))))
    print("%s  (%d bytes)" % (png, write_png(png)))
    return 0


if __name__ == "__main__":
    sys.exit(main())
